# Generated by Django 5.0.6 on 2024-07-21 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciepeapp', '0002_sellrecipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellrecipe',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
