# Generated by Django 5.0.6 on 2024-07-23 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciepeapp', '0005_remove_cartitem_date_added_remove_cartitem_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reciepeapp.recipe'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='products',
            field=models.ManyToManyField(through='reciepeapp.CartItem', to='reciepeapp.recipe'),
        ),
    ]
