# Generated by Django 5.0.6 on 2024-07-23 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciepeapp', '0006_alter_cartitem_product_alter_shoppingcart_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reciepeapp.sellrecipe'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='products',
            field=models.ManyToManyField(through='reciepeapp.CartItem', to='reciepeapp.sellrecipe'),
        ),
    ]
