# Generated by Django 5.0.7 on 2024-08-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reciepeapp", "0007_alter_cartitem_product_alter_shoppingcart_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="price",
            field=models.FloatField(default=100),
        ),
    ]
