# Generated by Django 5.0.7 on 2024-08-02 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reciepeapp", "0008_recipe_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="reciepeapp.recipe"
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="shoppingcart",
            name="products",
            field=models.ManyToManyField(
                through="reciepeapp.CartItem", to="reciepeapp.recipe"
            ),
        ),
        migrations.DeleteModel(
            name="Sellrecipe",
        ),
    ]
