# Generated by Django 5.0.7 on 2024-08-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reciepeapp", "0015_orderedproduct_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_address",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
