# Generated by Django 5.0.7 on 2024-08-09 08:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reciepeapp", "0016_alter_order_delivery_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.CharField(
                default=uuid.uuid4, editable=False, max_length=90, unique=True
            ),
        ),
    ]
